version: '3'
services:
  travelhelpsquad-sales-site:
    container_name: travelhelpsquad-sales-site
    build:
      dockerfile: Dockerfile
      context: .
      target: runner
    ports:
      - "80:80"
      - "443:443"